### PR TITLE
chore: update API links in docs

### PR DESCRIPTION
**Pull request by xadahiya**
Updated API links
- https://uniswapv2.powerloom.io/api/
- https://quickswap-polygon.powerloom.io/api/
- https://sushiswap-eth.powerloom.io/api/

### CODE REVIEW

**Review by SwaroopH — APPROVED** [review]
LGTM! Could you reset the package-lock and yarn.lock changes. No need to commit local ones unless there was a real change to package.json

**Comment by xadahiya** [comment]
Updated, merging now!

**Comment by SwaroopH** [comment]
Deployed. We need to update [this](https://pooler-docs.powerloom.io/API/overview) page as well but let's open another PR for that along with moving dashboard to a different URL.

**Comment by xadahiya** [comment]
Yeah, let me know when you've moved the dashboard to a different url. I'll raise a separate PR to fix front page.

**Comment by SwaroopH** [comment]
Now up at: https://pooler-api-dashboard.powerloom.io

**Comment by xadahiya** [comment]
Got it! Will create a PR today.

**Pull request merged**
